# Generated by Django 4.0.5 on 2022-07-13 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopas', '0005_cart_orderline_delete_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderline',
            name='cart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_lines', to='shopas.cart', verbose_name='Cart'),
        ),
    ]
