# Generated by Django 4.0.5 on 2022-07-13 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopas', '0006_alter_orderline_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='status',
            field=models.CharField(blank=True, choices=[('a', 'Accepted'), ('i', 'In Progress'), ('d', 'Done'), ('c', 'Cancelled'), ('k', 'Cart')], default='k', help_text='Status', max_length=1),
        ),
    ]
